# Generated by Django 5.1.5 on 2025-02-14 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=50, unique=True)),
                ("model", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("organization", "Organization Owned"),
                            ("rented", "Rented"),
                        ],
                        default="organization",
                        max_length=20,
                    ),
                ),
                (
                    "rental_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rental_price_per_day",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transportrequest",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transportrequest",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.vehicle",
            ),
        ),
    ]
