# Generated by Django 5.1.5 on 2025-02-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_vehicle_transportrequest_driver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportrequest",
            name="current_approver_role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Employee"),
                    (2, "Department Manager"),
                    (3, "Finance Manager"),
                    (4, "Transport Manager"),
                    (5, "CEO"),
                    (6, "Driver"),
                    (7, "System Admin"),
                ],
                default=2,
            ),
        ),
    ]
