# Generated by Django 5.1.5 on 2025-02-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="rental_price_per_day",
        ),
    ]
