# Generated by Django 5.1.6 on 2025-03-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_vehicle_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transportrequest",
            name="driver",
        ),
    ]
