# Generated by Django 5.1.6 on 2025-03-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_transportrequest_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("in_use", "In Use"),
                    ("service", "In Service"),
                    ("maintenance", "Under Maintenance"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
