# Generated by Django 5.1.6 on 2025-03-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_vehicle_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="is_available",
        ),
    ]
