# Generated by Django 5.1.5 on 2025-01-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Employee"),
                    (2, "Department Manager"),
                    (3, "Finance Manager"),
                    (4, "Transport Manager"),
                    (5, "CEO"),
                    (6, "Driver"),
                    (7, "System Admin"),
                ],
                default=1,
            ),
        ),
    ]
