# Generated by Django 5.1.5 on 2025-01-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatushistory",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
