# Generated by Django 5.1.5 on 2025-01-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_alter_userstatushistory_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatushistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
