# Generated by Django 5.1.5 on 2025-01-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0005_alter_userstatushistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userstatushistory",
            name="status",
            field=models.CharField(
                choices=[("approve", "Approved"), ("reject", "Rejected")], max_length=20
            ),
        ),
    ]
